<?php
// $Id$

/**
 * @file
 *   Chargify API Module.
 *
 *   Built by Sprocket.
 *   http://sprocketcreative.com
 */

/**
 * Implementation of hook_menu().
 */
function chargify_api_menu() {
  $items = array();

  $items['admin/settings/chargify'] = array(
    'title' => 'Chargify',
    'description' => 'Configure Chargify settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('chargify_api_settings_form'),
    'access arguments' => array('administer chargify'),
    'file' => 'chargify_api.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function chargify_api_perm() {
  return array('administer chargify');
}

/**
 * Starts a new Chargify Connection or returns the static connector.
 */
function chargify_api_connector() {
  static $connector = NULL;

  if (is_null($connector)) {
    chargify_api_include_api();
    $connector = new chargify_connector();
  }

  return $connector;
}

/**
 * Return all products.
 */
function chargify_api_products_get() {
  $connector = chargify_api_connector();

  return $connector->products_get();
}

/**
 * Returns a chargify product, by ID or handle.
 *
 * @param $value
 *   The numeric id or string handle.
 * @param $type
 *   Either 'id' or 'handle' depending on $value.
 * @return
 *   A chargify_product object.
 */
function chargify_api_product_get($value, $type = 'id') {
  $connector = chargify_api_connector();

  return $connector->product_get($value, $type);
}

/**
 * Load up a Chargify Customer.
 *
 * @param $value
 *   The chargify id or reference.
 * @param $type
 *   Either 'id' or 'reference' depending on whether the value is a chargify id or 
 *   reference.  Defaults to 'id'.
 */
function chargify_api_customer_get($value, $type = 'id') {
  $connector = chargify_api_connector();

  return $connector->customer_get($value, $type);
}

/**
 * Create a new subscription.
 *
 * @param $data
 *   The data to be posted to Chargify
 * @param $data_type
 *   The type of data, 'xml' or 'json'.
 */
function chargify_api_subscription_create($data, $data_type = 'xml') {
  $connector = chargify_api_connector();

  return $connector->create_subscription($data, $data_type);
}

/**
 * Return all subscriptions for a specific customer.
 *
 * @param $id
 *   The chargify customer id.
 */
function chargify_api_customer_get_subscriptions($id) {
  $connector = chargify_api_connector();

  return $connector->customer_get_subscriptions($id);
}

/**
 * Include Chargify API wrapper class.
 */
function chargify_api_include_api() {
  static $finished = FALSE;

  if ($finished) {
    return;
  }

  $files = array('chargify_connector', 'chargify_credit_card', 'chargify_customer', 'chargify_product', 'chargify_subscription');

  foreach ($files as $file) {
    chargify_api_include($file);
  }

  $finished = TRUE;
}

/**
 * Include Chargify includes.
 */
function chargify_api_include($file) {
  static $included = array();

  if (!isset($included[$file])) {
    module_load_include('inc', 'chargify_api', "includes/$file");
  }

  $included[$file] = TRUE;
}